در سلول زیر بخش مربوط به ترانهاده را کامل کنید

In [8]:
def transpose_matrix(a):
    result_transpose = []
    for elements in range(len(a)):
        for i in range(len(a)):
            result_transpose[elements][i]=a[i][elements]
    return result_transpose

در سلول زیر بخش مربوط به ضرب را کامل کنید


In [14]:
def multiplication_matrix(a, b):
    result_multiplication = []
    for elements1 in range(len(a)):
        for elements2 in range(len(b)):
            pass

در سلول زیر بخش مربوط به جمع را کامل کنید



In [10]:
def addition_matrix(a, b):
    result_addition = []
    for elements1 in range(len(a)):
        for elements2 in range(len(b)):
            if(elements1==elements2):
                result_addition=a[elements1]+b[elements2]
    return result_addition 

در این قسمت به کاربر یک منو نمایش دهید تا عملیات مورد نظر خودش را انتخاب کند


In [13]:
n = input('Please Enter What You Want to Calculate')
first_matrix = input()
if n == '1':
    transpose_matrix(first_matrix)
elif n ==  '2':
    second_matrix = input()
    multiplication_matrix(first_matrix, second_matrix)
elif n == '3':
    second_matrix = input()
    addition_matrix(first_matrix, second_matrix)


Please Enter What You Want to Calculate 3
 [[4,0,0,3,0,1,1,2,1,2,9]]


In [27]:
#transpose
import numpy as np

arr1 = np.array([[4,0,0,3,0,1,1,2,1,2,9]])

arr1_transpose = arr1.transpose()
arr1_transpose

array([[4],
       [0],
       [0],
       [3],
       [0],
       [1],
       [1],
       [2],
       [1],
       [2],
       [9]])

In [4]:
#multiplication
import numpy as np
b=np.array([[4,0,0,3,0,1,1,2,1,2,9]])
c=b.transpose()
d=c.dot(b)
#b@c
b.dot(c)

array([[117]])

In [33]:
#addition
import numpy as np
b=np.array([[4,0,0,3,0,1,1,2,1,2,9]])
c=b.transpose()
d=b.dot(c)
np.add(b, d)

array([[121, 117, 117, 120, 117, 118, 118, 119, 118, 119, 126]])