در سلول زیر بخش مربوط به ترانهاده را کامل کنید

In [8]:
def transpose_matrix(a):
    result_transpose = []
    for elements in range(len(a)):
        for i in range(len(a)):
            result_transpose[elements][i]=a[i][elements]
    return result_transpose

در سلول زیر بخش مربوط به ضرب را کامل کنید


In [7]:
def multiplication_matrix(a, b):
    result_multiplication = []
    for elements1 in range(len(a)):
        for j in range(len(b[0])):
            for elements2 in range(len(b)):
                    result_multiplication[elements1][j]+=a[elements1][elements2]*b[elements2][j]

در سلول زیر بخش مربوط به جمع را کامل کنید



In [10]:
def addition_matrix(a, b):
    result_addition = []
    for elements1 in range(len(a)):
        for elements2 in range(len(b)):
            if(elements1==elements2):
                result_addition=a[elements1]+b[elements2]
    return result_addition 

در این قسمت به کاربر یک منو نمایش دهید تا عملیات مورد نظر خودش را انتخاب کند


In [5]:
n = input('Please Enter What You Want to Calculate')
first_matrix = input()
if n== '1':
    # transpose_matrix(first_matrix)
    #print(transpose_matrix(first_matrix))
    m=transpose_matrix(first_matrix)
    print(m)
elif n ==  '2':
    second_matrix = input()
    m=multiplication_matrix(first_matrix, second_matrix)
    print(m)
elif n == '3':
    second_matrix = input()
    m=addition_matrix(first_matrix, second_matrix)
    print(m)


Please Enter What You Want to Calculate 2
 [[4,0,0,3,0,1,1,2,1,2,9]]


In [27]:
#transpose
import numpy as np

arr1 = np.array([[4,0,0,3,0,1,1,2,1,2,9]])

arr1_transpose = arr1.transpose()
arr1_transpose

array([[4],
       [0],
       [0],
       [3],
       [0],
       [1],
       [1],
       [2],
       [1],
       [2],
       [9]])

In [2]:
#multiplication
import numpy as np
b=np.array([[4,0,0,3,0,1,1,2,1,2,9]])
c=np.array([[16],
       [0],
       [0],
       [9],
       [0],
       [1],
       [1],
       [4],
       [1],
       [4],
       [81]])
#b@c
b.dot(c)

array([[839]])

In [3]:
#addition
import numpy as np
b=np.array([[4,0,0,3,0,1,1,2,1,2,9]])
c=np.array([[16],
       [0],
       [0],
       [9],
       [0],
       [1],
       [1],
       [4],
       [1],
       [4],
       [81]])
np.add(b, c)

array([[20, 16, 16, 19, 16, 17, 17, 18, 17, 18, 25],
       [ 4,  0,  0,  3,  0,  1,  1,  2,  1,  2,  9],
       [ 4,  0,  0,  3,  0,  1,  1,  2,  1,  2,  9],
       [13,  9,  9, 12,  9, 10, 10, 11, 10, 11, 18],
       [ 4,  0,  0,  3,  0,  1,  1,  2,  1,  2,  9],
       [ 5,  1,  1,  4,  1,  2,  2,  3,  2,  3, 10],
       [ 5,  1,  1,  4,  1,  2,  2,  3,  2,  3, 10],
       [ 8,  4,  4,  7,  4,  5,  5,  6,  5,  6, 13],
       [ 5,  1,  1,  4,  1,  2,  2,  3,  2,  3, 10],
       [ 8,  4,  4,  7,  4,  5,  5,  6,  5,  6, 13],
       [85, 81, 81, 84, 81, 82, 82, 83, 82, 83, 90]])