در سلول زیر بخش مربوط به ترانهاده را کامل کنید

In [25]:
import numpy as np
def transpose_matrix(input):
    b=np.array(input)
    a=np.matrix(b)
    result_transpose =np.zeros(len(a),len(a[0]))
    for elements in range(len(a)):
        for i in range(len(a[0])):
            result_transpose[elements][i]=a[i][elements]
    return result_transpose
transpose_matrix([4,0,0,3,0,1,1,2,1,2,9])

<class 'TypeError'>: Cannot interpret '1' as a data type

در سلول زیر بخش مربوط به ضرب را کامل کنید


In [13]:
def multiplication_matrix(a, b):
    result_multiplication =np.zeros(len(a),len(a[0]))
    for elements1 in range(len(a)):
        for j in range(len(b[0])):
            r=0
            for elements2 in range(len(b)):
                r+=a[elements1][elements2]*b[elements2][j]
            result_multiplication[elements1][j]=r
    return result_multiplication

در سلول زیر بخش مربوط به جمع را کامل کنید



In [11]:
def addition_matrix(a, b):
    result_addition =np.zeros(len(a),len(a[0]))
    for elements1 in range(len(a)):
        for elements2 in range(len(b)):
            if(elements1==elements2):
                result_addition[elements1][elements2]=a[elements1][elements2]+b[elements1][elements2]
    return result_addition 

در این قسمت به کاربر یک منو نمایش دهید تا عملیات مورد نظر خودش را انتخاب کند


In [10]:
n = input('Please Enter What You Want to Calculate')
first_matrix = input()
if n== '1':
    # transpose_matrix(first_matrix)
    #print(transpose_matrix(first_matrix))
    m=transpose_matrix(first_matrix)
    print(m)
elif n ==  '2':
    second_matrix = input()
    m=multiplication_matrix(first_matrix, second_matrix)
    print(m)
elif n == '3':
    second_matrix = input()
    m=addition_matrix(first_matrix, second_matrix)
    print(m)


Please Enter What You Want to Calculate 1
 [[4,0,0,3,0,1,1,2,1,2,9]]


In [19]:
#transpose
import numpy as np

arr1 = np.array([4,0,0,3,0,1,1,2,1,2,9])
arr2 = numpy.matrix(arr1)
arr1_transpose = arr2.transpose()
arr1_transpose

matrix([[4],
        [0],
        [0],
        [3],
        [0],
        [1],
        [1],
        [2],
        [1],
        [2],
        [9]])

In [21]:
#multiplication
import numpy as np
b=np.array([4,0,0,3,0,1,1,2,1,2,9])
c=np.array([16,0,0,9,0,1,1,4,1,4,81])
a = numpy.matrix(b)
d = numpy.matrix(c)
e = numpy.transpose(d)
final = numpy.matrix.__mul__(a,e)
final

matrix([[839]])

In [22]:
#addition
import numpy as np
b=np.array([4,0,0,3,0,1,1,2,1,2,9])
c=np.array([16,0,0,9,0,1,1,4,1,4,81])
a = numpy.matrix(b)
d = numpy.matrix(c)
e = numpy.transpose(a)
f = numpy.transpose(d)
final = numpy.matrix.__add__(e,f)
final

matrix([[20],
        [ 0],
        [ 0],
        [12],
        [ 0],
        [ 2],
        [ 2],
        [ 6],
        [ 2],
        [ 6],
        [90]])