In [7]:
#1
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(np.add(b, c))

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [27]:
#2
import numpy as np
b=np.array([[0,0,1],[0,0,1],[0,0,0]])
c=np.array([[1,1,0],[0,0,0],[1,0,1]])
#b@c
print(b.dot(c))
#zarb matrix
#zarb deraye be deraye:b*c

[[1 0 1]
 [1 0 1]
 [0 0 0]]


In [25]:
#3
import numpy as np
a=np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [3]:
#4
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6],[7, 8,9], [10, 11, 12]]])
print(arr,arr.ndim)
#arr.ndim bode arraye khoroji midahad

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]] 3


In [32]:
#5
import numpy as np
print(np.arange(1,100,4))

[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]


In [25]:
#6
import numpy as np
b=np.array([[7,8,9]])
c=np.array([[9,9,9]])
#anasore moshtarak to in tabe hastn
print(np.intersect1d(b,c))
#andise moshtarak ha toye b
a=np.where(b==np.intersect1d(b,c))
#andise moshtarak ha toye c
d=np.where(c==np.intersect1d(b,c))
print(a,d)

[9]
(array([0], dtype=int32), array([2], dtype=int32)) (array([0, 0, 0], dtype=int32), array([0, 1, 2], dtype=int32))


In [33]:
#7
import numpy as np
print(np.linspace( 50, 150, 10 ))

[ 50.          61.11111111  72.22222222  83.33333333  94.44444444
 105.55555556 116.66666667 127.77777778 138.88888889 150.        ]


In [2]:
#8
import numpy as np
print(np.full((6, 4), 2))

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
