In [38]:
#1
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[9,8,7],[6,5,4],[3,2,1]])
# a=np.sum(b,c)
print(b+c)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [27]:
#2
import numpy as np
b=np.array([[0,0,1],[0,0,1],[0,0,0]])
c=np.array([[1,1,0],[0,0,0],[1,0,1]])
#b@c
print(b.dot(c))
#zarb matrix
#zarb deraye be deraye:b*c

[[1 0 1]
 [1 0 1]
 [0 0 0]]


In [25]:
#3
import numpy as np
a=np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [36]:
#4

In [32]:
#5
import numpy as np
print(np.arange(1,100,4))

[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]


In [ ]:
#6

In [33]:
#7
import numpy as np
print(np.linspace( 50, 150, 10 ))

[ 50.          61.11111111  72.22222222  83.33333333  94.44444444
 105.55555556 116.66666667 127.77777778 138.88888889 150.        ]


In [ ]:
#8